before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarm:
      - 6
      - 7
    ldflags:
      - -s -w
dockers:
  -
    goos: linux
    goarch: amd64
    image_templates:
      - "systemli/etherpad-toolkit:{{ .Tag }}"
      - "systemli/etherpad-toolkit:{{ .Major }}"
      - "systemli/etherpad-toolkit:{{ .Major }}.{{ .Minor }}"
      - "systemli/etherpad-toolkit:latest"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
